import java.lang.System
import java.lang.Throwable
import java.util.Date
import java.lang.RuntimeException
import java.lang.String
import java.lang.Object
import java.lang.Exception
class Lilethhne/vzhqwhfh/rowjegdn/bkuipc2/Oeqrng6; extends Object
{
	void Lilethhne/vzhqwhfh/rowjegdn/bkuipc2/Oeqrng6;(){
		this.Object();
		return;
	}
	
	void dpmnci8(String[] p0){
		p0.println("Hello");
		return;
	}
	
	void hgfoom12(String[] p0){
		p0.println("Hello");
		return;
	}
	
	void tgkqqk10(String[] p0){
		p0.println("Hello");
		return;
	}
	
	void xdolrb1(String[] p0){
		p0.println("Hello");
		return;
	}
	
	void cxyltf5(){
		try{
			throw new Exception("Failed");
		}
		catch (Exception v0){
			goto catch_0;
		}
catch_0:
		throw new RuntimeException(new Exception("Failed"));
	}
	
	void dywseg6(){
		try{
			throw new Exception("Failed");
		}
		catch (Exception v0){
			goto catch_0;
		}
catch_0:
		throw new RuntimeException(new Exception("Failed"));
	}
	
	Date edqwwj9(){
		return new Date();
	}
	
	void iezlzp15(){
		try{
			throw new Exception("Failed");
		}
		catch (Exception v0){
			goto catch_0;
		}
catch_0:
		throw new RuntimeException(new Exception("Failed"));
	}
	
	void jcmvmd3(){
		try{
			throw new Exception("Failed");
		}
		catch (Exception v0){
			goto catch_0;
		}
catch_0:
		throw new RuntimeException(new Exception("Failed"));
	}
	
	void kubthr17(){
		try{
			throw new Exception("Failed");
		}
		catch (Exception v0){
			goto catch_0;
		}
catch_0:
		throw new RuntimeException(new Exception("Failed"));
	}
	
	void osahbh7(){
goto_0:
		if (0 >= 10) goto cond_0;
		v0 = 0 + 0x1;
		goto goto_0;
cond_0:
		return;
	}
	
	void rfstgo14(){
		try{
			throw new Exception("Failed");
		}
		catch (Exception v0){
			goto catch_0;
		}
catch_0:
		throw new RuntimeException(new Exception("Failed"));
	}
	
	void rqsxfe4(){
		try{
			throw new Exception("Failed");
		}
		catch (Exception v0){
			goto catch_0;
		}
catch_0:
		throw new RuntimeException(new Exception("Failed"));
	}
	
	Date shfsjn13(){
		return new Date();
	}
	
	void sqzsnl11(){
goto_0:
		if (0 >= 10) goto cond_0;
		v0 = 0 + 0x1;
		goto goto_0;
cond_0:
		return;
	}
	
	void wqefda0(){
		try{
			throw new Exception("Failed");
		}
		catch (Exception v0){
			goto catch_0;
		}
catch_0:
		throw new RuntimeException(new Exception("Failed"));
	}
	
	Date yysxic2(){
		return new Date();
	}
	
	void zqjptq16(){
		try{
			throw new Exception("Failed");
		}
		catch (Exception v0){
			goto catch_0;
		}
catch_0:
		throw new RuntimeException(new Exception("Failed"));
	}
	
}
